version: '3'
services:
  http1:
    build:
      context: ./http1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  http2:
    build:
      context: ./http2
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  h2load:
    build:
      context: ./h2load
      dockerfile: Dockerfile
    depends_on:
      - http1
      - http2
    entrypoint: ["sh", "-c", "sleep 2; h2load -n100000 -c100 -m100 --h1 http://http1:8080; h2load -n100000 -c100 -m100 https://http2:8081"]
